version: '3'

networks:
  my_network:
    name: my_network
    driver: bridge

volumes:
  WP:
    driver: local
    name: WP
    driver_opts:
      type: none
      o: bind
      device: /home/swautele/data/wordpress
  DB:
    driver: local
    name: DB
    driver_opts:
      type: none
      o: bind
      device: /home/swautele/data/mariadb

services:
  nginx:
    container_name: nginx
    restart: on-failure
    build: ./requirements/nginx
    ports: 
      - "443:443"
    volumes:
      - WP:/var/www/html/
    networks:
      - my_network
    depends_on: 
      - wordpress
  mariadb:
    container_name: mariadb
    restart: on-failure
    build: ./requirements/mariadb
    ports: 
      - "3306:3306"
    env_file: 
      - ./.env
    volumes:
      - DB:/var/lib/mysql/
    networks:
      - my_network
  wordpress:
    container_name: wordpress
    restart: on-failure
    build: ./requirements/wordpress
    ports: 
      - "9000:9000"
    env_file: 
      - ./.env
    depends_on: 
      - mariadb
    volumes:
      -  WP:/var/www/html/
    networks: 
      - my_network
     

