CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'swautele'@'%' IDENTIFIED BY '1234567890';
GRANT ALL PRIVILEGES ON wordpress.* TO 'swautele'@'%';

-- Creating root user
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1234567890';
FLUSH PRIVILEGES;